// ESTE ARCHIVO ESTÁ OBSOLETO Y HA SIDO REEMPLAZADO POR LA FUNCIONALIDAD DE SUPABASE STORAGE EN supabaseService.ts
// SE MANTIENE SOLO COMO REFERENCIA VACÍA PARA EVITAR ERRORES DE COMPILACIÓN SI ALGO LO IMPORTA.
export {};